### ISSUE TITLE
Code contains just the readme

### ISSUE THREAD

**Issue by werdahias** [scrivanolabs/ScrivanoForLinux#1]
the code contains just the readme

**Comment by daljit97** [comment]
Hi @CountOmega, Scrivano is not open source. This repository only contains the binary releases. I understand this might be misleading, so I'll add a notice in the readme file about this.

**Comment by scrivanolabs** [comment]
Hi @CountOmega, Scrivano is not open source. This repository only contains the binary releases for the Linux version. I understand this might be misleading, so I will add a disclaimer in the readme file.
