### ISSUE TITLE
Only works in full screen mode (0.17 versions)

### ISSUE THREAD

**Issue by DavidPGcch** [scrivanolabs/ScrivanoForLinux#15]
On full screen :smiley: 
![image](https://github.com/scrivanolabs/ScrivanoForLinux/assets/85504605/390501f3-723f-4257-9fee-e24ae24884ad)
Full screen off :cry:  , I don't know what to do
![image](https://github.com/scrivanolabs/ScrivanoForLinux/assets/85504605/605ef44c-9ca5-48c5-b4ee-cf5ab498481b)

**Comment by scrivanolabs** [comment]
Hi, please specify the operating system and the hardware you're using and the specific version of Scrivano. Also are you on X11 or Wayland?

**Comment by DavidPGcch** [comment]
> Hi, please specify the operating system and the hardware you're using and the specific version of Scrivano. Also are you on X11 or Wayland?

Scrivano 0.17.6 & 0.17.7
Debian GNU/Linux 12 (bookworm), Wayland
Gigabyte Technology Co., Ltd. A320M-S2H
AMD Ryzen™ 5 PRO 4650G with Radeon™ Graphics × 12

**Comment by scrivanolabs** [comment]
What happens if you add the following line to `Scrivano.sh` script (after line 22)?

`export QT_QPA_PLATFORM="xcb"`

**Comment by DavidPGcch** [comment]
The program does not open, I think that for the moment I will continue with versions 0.16
I don’t know if it has anything to do with it, but I’m using GNOME 43.6 although in version 0.16 this does not happen
