### ISSUE TITLE
Auto save causing Scrivano to crash and my system to freeze

### ISSUE THREAD

**Issue by henrispriet** [scrivanolabs/ScrivanoForLinux#17]
I believe the auto save is causing Scrivano to crash. It kept randomly crashing, and I noticed that saving after every few strokes prevented it. Also when I upped the auto saving interval from 2 to 30 minutes, it crashed significantly less often.
Opening a file that just crashed right afterwards often causes it to crash again.

Please add an option to disable auto-save (tbh I was surprised that there wasn't one to begin with). And it'd be nice if the crashing was fixed too of course.

I'm using Ubuntu 22.04.3 LTS and I believe the latest version of Scrivano.

**Comment by henrispriet** [comment]
Hi, thank you for your incredibly swift response.

> Could you please share the hardware details of your device?

Here is a screenshot of the Ubuntu Settings About section:
![image](https://github.com/scrivanolabs/ScrivanoForLinux/assets/36509362/9641b2fd-822d-4f20-9c6c-306947b4e9a7)

> Could you please confirm that you're using version 0.18.11?

I am indeed using Scrivano 0.18.11.

> Is there a file you can consistently reproduce this with?

There is,actually. Here it is:
[ex_H3.zip](https://github.com/scrivanolabs/ScrivanoForLinux/files/13927573/ex_H3.zip)

**Comment by scrivanolabs** [comment]
Ok, thanks for reporting this. After testing with your file, it seems that the app crashed due a bug in the rendering logic (effectively due to  a division by zero). I have just submitted a new release (0.18.12) which should fix the problem.

**Comment by henrispriet** [comment]
Cool, thanks for the fix!
I use a Wacom Volito that I had lying around.
