### ISSUE TITLE
executable not working

### ISSUE THREAD

**Issue by CountOmega** [scrivanolabs/ScrivanoForLinux#2]
When I run ./Scrivano.sh from the source sir, I get the following error:
`/home/user/Downloads/Scrivano0911/bin/Scrivano: error while loading shared libraries: libharfbuzz-subset.so.0: cannot open shared object file: No such file or directory`

**Comment by scrivanolabs** [comment]
Can you share what distro are you using (and the version)?

**Comment by CountOmega** [comment]
Debian testing/unstable

**Comment by scrivanolabs** [comment]
@CountOmega I've just uploaded a new version tested on a clean Ubuntu install. It should also work on Debian Unstable, if you try, please let me know if it works for you.
