### ISSUE TITLE
Unable to exit from Full Screen Once Entered in Linux 

### ISSUE THREAD

**Issue by sanjeev45** [scrivanolabs/ScrivanoForLinux#22]
Unable to Exit from full screen need to closed the app directly to exit from there ctrl+f11 does not work once it entered the full screen Mode.

**Comment by sanjeev45** [comment]
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Comment by sanjeev45** [comment]
Anything Else.

**Comment by EkiciLP** [comment]
Same Issue here on nobara linux with the flatpak version
