### ISSUE TITLE
Flatpak/deb/snap/appimage version

### ISSUE THREAD

**Issue by dtantono** [scrivanolabs/ScrivanoForLinux#3]
Hi
to cover wider linux distros. Is it possible to get this app on Flatpak/deb/snap/appimage?

**Comment by scrivanolabs** [comment]
Hi @dtantono, a Flatpak or an Appimage might be released in the future. For now, the app should work on most distros. I've tested it on Ubuntu, Manjaro, Fedora and Debian. Did you have any trouble running it on your particular distro? If yes, which one?

**Comment by dtantono** [comment]
I use ubuntu 20.04 and it looks fine. The reason for extra .deb package because Debian based distro have similar feature called deb-get (https://github.com/wimpysworld/deb-get). it would be nice if we have other alternatives. what do you think?

**Comment by scrivanolabs** [comment]
I have no plan of releasing deb files as they are not supported on all distros. Flatpak or an Appimage is on my list.

**Comment by scrivanolabs** [comment]
This is now done. You can download [Scrivano from Flathub](https://flathub.org/apps/details/com.github.scrivanolabs.scrivano)
