### ISSUE TITLE
exe/msi files for Windows version

### ISSUE THREAD

**Issue by dtantono** [scrivanolabs/ScrivanoForLinux#4]
Hello
Since windows have winget https://github.com/microsoft/winget-cli and chocolatey https://github.com/chocolatey/choco and also not everyone likes UWP apps. Is it possible to got the windows version in exe/msi format?

**Comment by scrivanolabs** [comment]
For Windows, I don’t have any plan to provide more release channels other than the Store. Note also that Scrivano is **not** a UWP app, it’s a standard Win32 app that is distributed on the Microsoft Store.
