### ISSUE TITLE
Crashing while using Free Eraser tool

### ISSUE THREAD

**Issue by giumatt** [scrivanolabs/ScrivanoForLinux#5]
Hi, I've find a bug while using the Free Eraser tool and I'm trying to erase a line made with the line tool and grid snapping: if I begin to erase one little portion of the line it will be deleted and then the app crashes and closes.

I'm using Scrivano on Arch Linux 5.17.8 with KDE Plasma 5.24.5.

**Comment by giumatt** [comment]
It happens consistently, whenever I write a line using the line tool and I try to erase it with the Free Eraser, but if I use the Standard Eraser I do not have any problem.

**Comment by scrivanolabs** [comment]
Ok thanks. What hardware are you using? (It'd be helpful if you could provide the model of the stylus you have if you're using one).

**Comment by scrivanolabs** [comment]
Hi, that should be enough. I'm planning to rewrite the logic for the free eraser soon and hope that will fix the crash issues. I'll update this thread once I do that.

**Comment by giumatt** [comment]
Thank you! Glad to have been helpful.

**Comment by giumatt** [comment]
Hi! Just checked today sorry for the delay, the issue appears to be solved, thank you very much! :)
