### ISSUE TITLE
Immediate crash on Wayland? 

### ISSUE THREAD

**Issue by RussH** [scrivanolabs/ScrivanoForLinux#6]
I guess it's just unsupported?

> May 18 15:53:30 russ-surfacepro systemd-coredump[15049]: Process 15025 (Scrivano) of user 1000 dumped core.
>                                                          
>                                                          Stack trace of thread 15046:
>                                                          #0  0x00007f7cd3685f44 n/a (/home/russh/Projects/Scrivano_0.11.4/lib/libskia.so + 0x3caf44)
>                                                          #1  0x00007f7cd3fa2808 n/a (/home/russh/Projects/Scrivano_0.11.4/lib/libQt5Core.so.5 + 0x29d808)
>                                                          #2  0x0000000001578540 n/a (n/a + 0x0)
>                                                          #3  0x00000000015682a0 n/a (n/a + 0x0)
> May 18 15:53:30 russ-surfacepro systemd[1]: systemd-coredump@4-15048-0.service: Succeeded.

[coredump.zip](https://github.com/scrivanolabs/ScrivanoForLinux/files/8717406/coredump.zip)

I've attached the coredump if it's useful?

**Comment by scrivanolabs** [comment]
Hi, yes. Scrivano hasn't been tested on Wayland. I was able to reproduce the crash on my machine too so I'm investigating the problem. Hope to have an update on this soon.

**Comment by scrivanolabs** [comment]
This has been fixed in the latest release.
