### ISSUE TITLE
No pressure-non-sensitive touchscreen support

### ISSUE THREAD

**Issue by novaisadumbass** [scrivanolabs/ScrivanoForLinux#9]
Hello, I am very interested in using this application, however it is not responsive to my simpleton, not-graphics-oriented touchscreen of my Nexdock 360. There are also no setting to enable the feature (as far as I know), like for example rNote has (but also has many more issues that make it unfit for my usage). Running Arch on a steam deck if it helps

**Comment by scrivanolabs** [comment]
Hi there, could you please expand on what exactly do you mean by "not responsive"? Is the app lagging? Or do you intend that you're not able to write with Scrivano using your touchscreen?
If it's the latter, could you please specify what input device you're using (e.g. fingers, stylus, mouse).

**Comment by novaisadumbass** [comment]
Hi, i am unable to write. Instead of writing my touch inputs just move the canvass. I´m using an active stylus (Goojodoq GD03), which is basically just a pen that simulates finger touch input - it works on all touchscreens if that makes sense.

**Comment by scrivanolabs** [comment]
Ok, I understand. Please note that the stylus you're using is not an active stylus, but a *capacitive* pen. This means that the laptop recognises it as an ordinary touch input. In the current version of Scrivano unfortunately there is no way to write using your fingers (and thus using a capacitive pen), but I hope to add an option in the settings to enable this feature.

**Comment by novaisadumbass** [comment]
Understood, hope to see it soon.
